version: "3"
services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  sqs:
    image: pakohan/elasticmq
    hostname: sqs
    ports:
      - 9324:9324

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "9510:9510"
    depends_on:
      - db
      - sqs
    volumes:
      - .:/code

  worker:
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/worker/Dockerfile
    depends_on:
      - django
    volumes:
      - .:/code

  nodejs:
    hostname: nodejs
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
      - "9008:9008"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/bower_components
